### ISSUE TITLE
question: facets ?

### ISSUE THREAD

**Issue by joeblew99** [bcampbell/qs#8]
wondering if you are considering including facets in this ?

**Comment by bcampbell** [comment]
I think facets are covered by bleve itself, aren't they?
eg:

```
query, _ := qs.Parse(queryString)
req := bleve.NewSearchRequest(query)
facet := bleve.NewFacetRequest("shoesize",1)
req.AddFacet("shoe size facet", facet)
results,err := myIndex.Search(req)
```

(disclaimer, I've not really played around with facets much)

**Comment by joeblew99** [comment]
Yes they are part of Bleve. I use them.
I was like your api, and so want to use it to also access facets.

The Bleve code only has a untyped json api which is aweful to use. Hence
why I like your golang api.

What do you think about supporting facets ?

**Comment by bcampbell** [comment]
I don't quite understand how facets would fit in to qs... it just takes a string, turns it into a Query, and that's it.
Can you give me any code examples of the sorts of things you'd like to see?

**Comment by joeblew99** [comment]
sorry about not following up & he confusion.
i see its supports all facets types (ranges, etc).
I assume though that after a search, you get the list of possible facets back each time, so a user can do iterative searches ? 
Is there any test data with test around ?
I just want to run it through its paces because i used bleve on a project a while ago and maintain the teats and test data was really a huge amount of work i found.
thats partly why i am enthusiastic about using this.

**Comment by joeblew99** [comment]
@bcampbell Does the explanation above help ?
Basically looking for an example to try out some ideas.
